export AUTH0_CLIENT_ID='0ozijLOMLWiIJmxMSwRYLZvozn54GEnk'
export AUTH0_CLIENT_SECRET='_0_ZmjVjwL2TEYWT_syIlfcYhFxFFr00O4L0tvzxuuIHVqj4nTGmwiZU8034hKz3'
export AUTH0_CALLBACK_URL='https://localhost:5000/login-results'
export AUTH0_DOMAIN='duncantalbot.au.auth0.com'
export AUTH0_AUDIENCE='https://golftracker'
export AUTH0_BASE_URL='https://duncantalbot.au.auth0.com'
export AUTH0_ALGORITHMS=['RS256'] 

export CLIENT_ID='OJexo9qKwUpl0eVyD9HIZklsxBKw7L3X'
export DATABASE_URL='postgresql://{}:{}@{}/{}".format('postgres', 'password','localhost:5432', golftracker'

export MEMBER_TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImhEZnpkaTJ6NHY5UHg2aGdmczZZQiJ9.eyJpc3MiOiJodHRwczovL2R1bmNhbnRhbGJvdC5hdS5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NWZjODc4MGI0Y2QzODkwMDZmYTMzYWE2IiwiYXVkIjpbImh0dHBzOi8vZ29sZnRyYWNrZXIiLCJodHRwczovL2R1bmNhbnRhbGJvdC5hdS5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjA2OTkzMjAxLCJleHAiOjE2MDcwNzk2MDEsImF6cCI6IjBvemlqTE9NTFdpSUpteE1Td1JZTFp2b3puNTRHRW5rIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsInBlcm1pc3Npb25zIjpbImRlbGV0ZTpldmVudHMiLCJnZXQ6ZXZlbnRzIiwicG9zdDpldmVudHMiLCJ1cGRhdGU6ZXZlbnRzIl19.Aw0hQf-Fx7VcbzZ0IDzpcagOm8twZ1pbR3rzsh6tTXh9YYHKdW9ioXPmVzGRFOyc_Vdl8MdYPz23RhMuq9YiPjb6Da-xLBkNCR5YU9Ldg_tCsAvHAtHjK_s-51fm7iwzhwCxjQ4YzM-ADQ6_FPrAri6NkKjJ2lMJuKWLDQ6s3V4G1zoKMXmlGveqk-ynUNqgmO_NaFITucc5sv0nSq0VzujsJYFXeH9XQu2LGHWNdZrGNH9sTSDHySR1bBcSWdYRZv39bOyXkqVMLLryPqWBnU3Rj5QlQKgRBXkBHKW4qDszGaKtLSDHjruSbnASL04dCof5Z7W0jTzC8oqSMxXcUw